steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - '--quiet'
    id: Deploy to App Engine
    dir: 'com-724-python-dashboard'  # Replace 'app' with the directory where your app.yaml is located
options:
  logging: 'CLOUD_LOGGING_ONLY'

timeout: '1200s'  # Adjust the timeout as needed